table DimGeo
	lineageTag: 76238376-8f7a-4d13-a229-a1a6ad5b5041

	column Region
		dataType: string
		lineageTag: 51abc571-8427-4250-8304-27ba483db6b1
		summarizeBy: none
		sourceColumn: Region

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 33605452-2e00-4e5f-b48a-4d8f5dce2207
		summarizeBy: none
		sourceColumn: Country

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 53c76887-33dd-4d90-b2b4-282091b66b6f
		summarizeBy: none
		sourceColumn: City

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column PostalCode
		dataType: string
		lineageTag: 69e48cdc-063d-4ef0-921d-73cba1ebc422
		summarizeBy: none
		sourceColumn: PostalCode

		annotation SummarizationSetBy = Automatic

	column GeoID
		dataType: string
		lineageTag: 7d37ec06-9424-41c3-8552-ac80778088c4
		summarizeBy: none
		sourceColumn: GeoID

		annotation SummarizationSetBy = Automatic

	partition DimGeo = m
		mode: import
		queryGroup: 'All Tables'
		source = ```
				let
				    // Load all files from the folder
				    SourceFolder = Folder.Files(Sources),
				    
				    // Filter to get the specific CSV file
				    FilteredFile = Table.SelectRows(SourceFolder, each [Name] = "DC Sales Information.csv"),
				    
				    // Get the file content
				    FileContent = Csv.Document(FilteredFile{0}[Content], [Delimiter=",", Columns=22, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    
				    // Promote headers
				    #"Promoted Headers" = Table.PromoteHeaders(FileContent, [PromoteAllScalars=true]),
				    
				    // Change column types
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{
				        {"OrderID", type text}, {"OrderDate", type date}, {"CustomerID", type text}, {"CustomerName", type text},
				        {"CustomerSegment", type text}, {"Region", type text}, {"Country", type text}, {"City", type text},
				        {"PostalCode", Int64.Type}, {"ProductID", type text}, {"ProductName", type text}, {"Category", type text},
				        {"SubCategory", type text}, {"SalesChannel", type text}, {"UnitsSold", Int64.Type}, {"UnitPrice", type number},
				        {"Revenue", type number}, {"Cost", type number}, {"Profit", type number}, {"Discount", type number},
				        {"PaymentMode", type text}, {"DeliveryDate", type date}
				    }),
				
				    // Remove duplicates
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type"),
				
				    // Create CustomerName2
				    #"Inserted Merged Column" = Table.AddColumn(#"Removed Duplicates", "Merged", each Text.Combine({"Customer_", [CustomerID]}), type text),
				    #"Reordered Columns" = Table.ReorderColumns(#"Inserted Merged Column",{"OrderID", "OrderDate", "CustomerID", "CustomerName", "Merged", "CustomerSegment", "Region", "Country", "City", "PostalCode", "ProductID", "ProductName", "Category", "SubCategory", "SalesChannel", "UnitsSold", "UnitPrice", "Revenue", "Cost", "Profit", "Discount", "PaymentMode", "DeliveryDate"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Merged", "CustomerName2"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"CustomerName"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"CustomerName2", "CustomerName"}}),
				
				    // Fix category names
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1","electronix","Electronics",Replacer.ReplaceText,{"Category"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Furnture","Furniture",Replacer.ReplaceText,{"Category"}),
				
				    // Sort and clean region
				    #"Sorted Rows" = Table.Sort(#"Replaced Value1",{{"Country", Order.Ascending}, {"City", Order.Ascending}, {"Region", Order.Ascending}, {"CustomerSegment", Order.Ascending}}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Sorted Rows","","Missing",Replacer.ReplaceValue,{"Region"}),
				
				    // Clean and format text
				    #"Trimmed Text" = Table.TransformColumns(Table.TransformColumnTypes(#"Replaced Value2", {{"PostalCode", type text}}, "en-US"),{{"Region", Text.Trim, type text}, {"Country", Text.Trim, type text}, {"City", Text.Trim, type text}, {"PostalCode", Text.Trim, type text}}),
				    #"Uppercased Text" = Table.TransformColumns(#"Trimmed Text",{{"Region", Text.Upper, type text}, {"Country", Text.Upper, type text}, {"City", Text.Upper, type text}, {"PostalCode", Text.Upper, type text}}),
				
				    // Final GeoID
				    #"Inserted Merged Column2" = Table.AddColumn(#"Uppercased Text", "Merged", each Text.Combine({[Region], "|", [Country], "|", [City], "|", [PostalCode]}), type text),
				    #"Renamed Columns3" = Table.RenameColumns(#"Inserted Merged Column2",{{"Merged", "GeoID"}}),
				
				    // Final formatting
				    #"Capitalized Each Word" = Table.TransformColumns(#"Renamed Columns3",{{"Region", Text.Proper, type text}, {"Country", Text.Proper, type text}, {"City", Text.Proper, type text}}),
				    #"Sorted Rows1" = Table.Sort(#"Capitalized Each Word",{{"OrderDate", Order.Descending}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Sorted Rows1",{"Region", "Country", "City", "PostalCode"}),
				    #"Trimmed Text1" = Table.TransformColumns(#"Removed Other Columns",{{"Region", Text.Trim, type text}, {"Country", Text.Trim, type text}, {"City", Text.Trim, type text}}),
				    #"Uppercased Text1" = Table.TransformColumns(#"Trimmed Text1",{{"Region", Text.Upper, type text}, {"Country", Text.Upper, type text}, {"City", Text.Upper, type text}}),
				    #"Inserted Merged Column1" = Table.AddColumn(#"Uppercased Text1", "Merged", each Text.Combine({[Region], "|", [Country], "|", [City], "|", [PostalCode]}), type text),
				    #"Removed Duplicates1" = Table.Distinct(#"Inserted Merged Column1"),
				    #"Capitalized Each Word1" = Table.TransformColumns(#"Removed Duplicates1",{{"Region", Text.Proper, type text}, {"Country", Text.Proper, type text}, {"City", Text.Proper, type text}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Capitalized Each Word1",{{"Merged", "GeoID"}})
				in
				    #"Renamed Columns2"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

