table DimDate
	lineageTag: 1da4ed62-da04-4dfb-adc5-2c682af91d3d

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0344815f-2fc6-4d5d-97bc-4f90c1c0e8f2
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 82b61342-134d-4fcb-b352-763871568dd2
			defaultHierarchy: LocalDateTable_549ac493-f2b7-4b90-856d-66dee238c1a7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Calendar Year'
		dataType: string
		lineageTag: 318f376b-5adb-4e8e-93c2-3a7aeb7d39d7
		summarizeBy: none
		sourceColumn: Calendar Year

		annotation SummarizationSetBy = Automatic

	column 'Year Offset'
		dataType: int64
		formatString: 0
		lineageTag: ef7f47af-f56b-4269-aad0-2ec766f6af33
		summarizeBy: sum
		sourceColumn: Year Offset

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: string
		lineageTag: ce0f3733-c20d-43b9-b4f5-28e2a87c9935
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year Offset'
		dataType: int64
		formatString: 0
		lineageTag: c0c27754-9e92-44bc-8231-c9f8b7e0d7f7
		summarizeBy: sum
		sourceColumn: Fiscal Year Offset

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 7dbb4e47-7ba0-4f6f-ab80-4af836dd23aa
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month'
		dataType: string
		lineageTag: 6ea83ae8-bef7-4d7b-9274-a8ae0bbcc092
		summarizeBy: none
		sourceColumn: Fiscal Month

		annotation SummarizationSetBy = Automatic

	column 'Month Offset'
		dataType: int64
		formatString: 0
		lineageTag: 37c25bdd-3310-45c8-a027-a77b2d8c58c4
		summarizeBy: sum
		sourceColumn: Month Offset

		annotation SummarizationSetBy = Automatic

	column 'Month Status'
		dataType: string
		lineageTag: eb73feac-d754-4f3d-83a5-bc31367e5016
		summarizeBy: none
		sourceColumn: Month Status

		annotation SummarizationSetBy = Automatic

	column LTM
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f4e04219-5c32-4425-b324-a564b2c0b46f
		summarizeBy: none
		sourceColumn: LTM

		annotation SummarizationSetBy = Automatic

	column PeriodNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: aff4c8d6-d392-4f99-8d53-54f7e575b02d
		summarizeBy: sum
		sourceColumn: PeriodNumberOfYear

		annotation SummarizationSetBy = Automatic

	column MonthNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: ce589ef9-c12f-4b9c-8ee4-39dbf63e41c3
		summarizeBy: sum
		sourceColumn: MonthNumberOfYear

		annotation SummarizationSetBy = Automatic

	column MonthLongName
		dataType: string
		lineageTag: 879d5841-9df9-4894-a0f4-c4efa7f6d0a9
		summarizeBy: none
		sourceColumn: MonthLongName

		annotation SummarizationSetBy = Automatic

	column MonthShortName
		dataType: string
		lineageTag: f882027d-4423-4808-a09c-1f5144c255ae
		summarizeBy: none
		sourceColumn: MonthShortName

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter'
		dataType: string
		lineageTag: 7a5387d7-91bc-4a57-8743-bdfe9a0a1e98
		summarizeBy: none
		sourceColumn: Fiscal Quarter

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: ba770b72-1da8-42f6-869c-0ab61b6ef3bf
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column QuarterNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: f573f271-130a-48c0-97f5-63da28f4ea12
		summarizeBy: sum
		sourceColumn: QuarterNumberOfYear

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter Offset'
		dataType: int64
		formatString: 0
		lineageTag: 71b0c2e5-30f9-4f14-ba44-38de227609f0
		summarizeBy: sum
		sourceColumn: Fiscal Quarter Offset

		annotation SummarizationSetBy = Automatic

	column StartOfWeek
		dataType: string
		lineageTag: 29cddb57-f353-483e-a18b-197b74b8752d
		summarizeBy: none
		sourceColumn: StartOfWeek

		annotation SummarizationSetBy = Automatic

	column WeekName
		dataType: string
		lineageTag: 0744eb18-3a4b-4a50-9ac2-773e48b667b5
		summarizeBy: none
		sourceColumn: WeekName

		annotation SummarizationSetBy = Automatic

	column 'Week Offset'
		dataType: int64
		formatString: 0
		lineageTag: f82a24b4-3ef5-4e04-96fe-f9edb133e5f3
		summarizeBy: sum
		sourceColumn: Week Offset

		annotation SummarizationSetBy = Automatic

	column 'Day Offset'
		dataType: int64
		formatString: 0
		lineageTag: a53b6fca-ed47-4fe9-a743-7a4f39ee34c2
		summarizeBy: sum
		sourceColumn: Day Offset

		annotation SummarizationSetBy = Automatic

	column DayOfMonth
		dataType: int64
		formatString: 0
		lineageTag: 7bc1b3aa-5713-4028-9b52-7f4bc991ffc2
		summarizeBy: sum
		sourceColumn: DayOfMonth

		annotation SummarizationSetBy = Automatic

	column Weekday
		dataType: string
		lineageTag: 199462bc-65ee-4069-b369-6a10fb45642e
		summarizeBy: none
		sourceColumn: Weekday

		annotation SummarizationSetBy = Automatic

	column WeekdayShortName
		dataType: string
		lineageTag: 02748085-a562-4546-ae88-8e1e25e89551
		summarizeBy: none
		sourceColumn: WeekdayShortName

		annotation SummarizationSetBy = Automatic

	column WeekdayNumber
		dataType: int64
		formatString: 0
		lineageTag: 75f0a0b2-64ef-415c-b51b-5a8999f3a33e
		summarizeBy: sum
		sourceColumn: WeekdayNumber

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a9f87175-4bee-463b-a810-1a9e3146d0a4
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column 'Half Year'
		dataType: string
		lineageTag: 17e2cc89-f9aa-4886-81e6-6e1422bbc0c3
		summarizeBy: none
		sourceColumn: Half Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Half Year'
		dataType: string
		lineageTag: e8bcfa81-3b3d-4e65-89ac-b398c2f4e57b
		summarizeBy: none
		sourceColumn: Fiscal Half Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Half Year Offset'
		dataType: int64
		formatString: 0
		lineageTag: 8c75e17c-2cdc-42b4-aa96-56eb66966562
		summarizeBy: sum
		sourceColumn: Fiscal Half Year Offset

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		queryGroup: 'All Tables'
		source = ```
				let
				    ListDates = List.Dates(#"StartDate", Number.From(#"EndDate" - #"StartDate")+1, #duration(1,0,0,0)),
				    #"Converted to Table" = Table.FromList(ListDates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
				    #"Added Calendar Date" = Table.AddColumn(#"Renamed Columns", "Calendar Date", each Date.AddMonths ([Date],#"Fiscal Year Reset")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Calendar Date",{{"Date", type date}, {"Calendar Date", type date}}),
				    #"Month Offset" = Table.AddColumn(#"Changed Type", "Month Offset", each (Date.Year([Date]) - Date.Year(Date.From(DateTime.LocalNow())))*12 
				+ Date.Month([Date]) - Date.Month(Date.From(DateTime.LocalNow()))),
				    #"Day Offset" = Table.AddColumn(#"Month Offset", "Day Offset", each Number.From((Date.From(DateTime.LocalNow()) - [Date])) * -1, type number),
				    #"Year Offset" = Table.AddColumn(#"Day Offset", "Year Offset", each (Date.Year(Date.From(DateTime.LocalNow())) - Date.Year([Date])) * -1),
				    #"Fiscal Year Offset" = Table.AddColumn(#"Year Offset", "Fiscal Year Offset", each if Date.Month(Date.From(DateTime.LocalNow())) > (12-#"Fiscal Year Reset")
				
				then 
				((Date.Year(Date.From(DateTime.LocalNow())) - Date.Year([Calendar Date])) * -1) -1
				
				else 
				
				(Date.Year(Date.From(DateTime.LocalNow())) - Date.Year([Calendar Date])) * -1),
				    #"Inserted Calendar Year" = Table.AddColumn(#"Fiscal Year Offset", "Calendar Year", each Date.Year([Date])),
				    #"Fiscal Year" = Table.AddColumn(#"Inserted Calendar Year", "Fiscal Year", each "FY" & Date.ToText([Calendar Date], "yy")),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Fiscal Year",{{"Year Offset", Int64.Type}, {"Calendar Year", type text}, {"Fiscal Year", type text}, {"Fiscal Year Offset", Int64.Type}}),
				    PeriodNumberOfYear = Table.AddColumn(#"Changed Type1" , "PeriodNumberOfYear", each Date.Month([Calendar Date])),
				    MonthNumberOfYear = Table.AddColumn(PeriodNumberOfYear, "MonthNumberOfYear", each Date.Month([Date]), Int64.Type),
				    MonthLongName = Table.AddColumn(MonthNumberOfYear, "MonthLongName", each Date.MonthName([Date]), type text),
				    MonthShortName = Table.AddColumn(MonthLongName, "MonthShortName", each Text.Start([MonthLongName], 3), type text),
				    #"Month Status" = Table.AddColumn(MonthShortName, "Month Status", each if [Month Offset] = 0 then " Current" else if [Month Offset] > 0 then "Future" else "Complete"),
				    Month = Table.AddColumn(#"Month Status", "Month", each [MonthShortName]
				 &" '"& 
				 Date.ToText([Date], "yy")),
				    #"Fiscal Month" = Table.AddColumn(Month, "Fiscal Month", each [MonthShortName]
				 &", "& 
				[Fiscal Year]),
				    #"Added LTM" = Table.AddColumn(#"Fiscal Month", "LTM", each if [Month Offset] > -13 and [Month Offset] < 0
				 then "True"
				 else "False"),
				    #"Fiscal Quarter" = Table.AddColumn(#"Added LTM", "Quarter", each "Q"& Text.From(Date.QuarterOfYear([Calendar Date]))),
				    #"Added QuarterNumberOfYear" = Table.AddColumn(#"Fiscal Quarter", "QuarterNumberOfYear", each Date.QuarterOfYear([Calendar Date])),
				    #"Fiscal Quarter Year" = Table.AddColumn(#"Added QuarterNumberOfYear", "Fiscal Quarter", each [Quarter]
				 &" '"& 
				 [Fiscal Year]),
				    #"Fiscal Quarter Offset" = Table.AddColumn(#"Fiscal Quarter Year", "Fiscal Quarter Offset", each ( Date.Year (Date.AddMonths([Date],#"Fiscal Year Reset")) 
				  - 
				   Date.Year(
				       Date.From(Date.AddMonths( DateTime.LocalNow(), #"Fiscal Year Reset") )
				            )
				  )*4 
				
				+ Date.QuarterOfYear (Date.AddMonths([Date],#"Fiscal Year Reset")) 
				
				- Date.QuarterOfYear (Date.AddMonths( DateTime.LocalNow(), #"Fiscal Year Reset"))),
				    #"Inserted DayOfMonth" = Table.AddColumn(#"Fiscal Quarter Offset", "DayOfMonth", each Date.Day([Date]), type number),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted DayOfMonth", "Weekday", each Date.DayOfWeekName([Date]), type text),
				    #"Inserted WeekdayShortName" = Table.AddColumn(#"Inserted Day Name", "WeekdayShortName", each Text.Start([Weekday], 3), type text),
				    #"Inserted WeekDayNumber" = Table.AddColumn(#"Inserted WeekdayShortName", "WeekdayNumber", each Date.DayOfWeek([Date]), type number),
				    IsWeekend = Table.AddColumn(#"Inserted WeekDayNumber", "IsWeekend", each Logical.From(if [WeekdayNumber]= 6 or [WeekdayNumber] = 0 then "TRUE" else "FALSE")),
				    #"Inserted End of Week" = Table.AddColumn(IsWeekend, "StartOfWeek", each Date.StartOfWeek([Date], Day.Monday)),
				    #"Added WeekName" = Table.AddColumn(#"Inserted End of Week", "WeekName", each Text.Combine
				(
				 {
				  "Week of ",
				  Date.ToText([StartOfWeek], "MMM"),
				
				  "-",
				  Date.ToText([StartOfWeek], "dd"),
				  ", '",
				  Date.ToText([StartOfWeek], "yy")
				  }
				)),
				    #"Week Offset" = Table.AddColumn(#"Added WeekName", "Week Offset", each (
				    Number.From((Date.From(Date.EndOfWeek(DateTime.LocalNow(), Day.Monday)) - [StartOfWeek]))
				 * -1) 
				 / 7),
				    #"Half Year" = Table.AddColumn(#"Week Offset", "Half Year", each if Number.RoundUp([PeriodNumberOfYear]/6)=1
				then "1st Half"
				else "2nd Half"),
				    #"Fiscal Half Year" = Table.AddColumn(#"Half Year", "Fiscal Half Year", each [Fiscal Year]&" "&[Half Year]),
				    #"Fiscal Half Year Offset" = Table.AddColumn(#"Fiscal Half Year", "Fiscal Half Year Offset", each [Fiscal Year Offset]*2
				
				+ 
				Number.RoundUp(
				(Date.Month([Calendar Date]) - Date.Month(Date.From(DateTime.LocalNow())))/6
				)-1),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Fiscal Half Year Offset",{{"Week Offset", type number}}),
				    #"Rounded Down" = Table.TransformColumns(#"Changed Type2",{{"Week Offset", Number.RoundDown, Int64.Type}}),
				    #"Sorted Rows" = Table.Sort(#"Rounded Down",{{"Date", Order.Ascending}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Sorted Rows",{"Date", "Month Offset", "Day Offset", "Year Offset", "Fiscal Year Offset", "Calendar Year", "Fiscal Year", "PeriodNumberOfYear", "MonthNumberOfYear", "MonthLongName", "MonthShortName", "Month Status", "Month", "Fiscal Month", "LTM", "Quarter", "QuarterNumberOfYear", "Fiscal Quarter", "Fiscal Quarter Offset", "DayOfMonth", "Weekday", "WeekdayShortName", "WeekdayNumber", "IsWeekend", "StartOfWeek", "WeekName", "Week Offset", "Half Year", "Fiscal Half Year", "Fiscal Half Year Offset"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Other Columns",{"Date", "Calendar Year", "Year Offset", "Fiscal Year", "Fiscal Year Offset", "Month", "Fiscal Month", "Month Offset", "Month Status", "LTM", "PeriodNumberOfYear", "MonthNumberOfYear", "MonthLongName", "MonthShortName", "Fiscal Quarter", "Quarter", "QuarterNumberOfYear", "Fiscal Quarter Offset", "StartOfWeek", "WeekName", "Week Offset", "Day Offset", "DayOfMonth", "Weekday", "WeekdayShortName", "WeekdayNumber", "IsWeekend"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Reordered Columns",{{"Calendar Year", type text}, {"Year Offset", Int64.Type}, {"Fiscal Year", type text}, {"Fiscal Year Offset", Int64.Type}, {"Month Status", type text}, {"Fiscal Month", type text}, {"Month", type text}, {"Month Offset", Int64.Type}, {"LTM", type logical}, {"PeriodNumberOfYear", Int64.Type}, {"MonthNumberOfYear", Int64.Type}, {"MonthLongName", type text}, {"MonthShortName", type text}, {"Fiscal Quarter", type text}, {"Quarter", type text}, {"QuarterNumberOfYear", Int64.Type}, {"Fiscal Quarter Offset", Int64.Type}, {"Week Offset", Int64.Type}, {"StartOfWeek", type text}, {"WeekName", type text}, {"Day Offset", Int64.Type}, {"DayOfMonth", Int64.Type}, {"WeekdayNumber", Int64.Type}, {"Weekday", type text}, {"WeekdayShortName", type text}, {"IsWeekend", type logical}, {"Half Year", type text}, {"Fiscal Half Year", type text}, {"Fiscal Half Year Offset", Int64.Type}}),
				    #"Sorted Rows1" = Table.Sort(#"Changed Type3",{{"Date", Order.Descending}})
				in
				    #"Sorted Rows1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

