table _Measure
	lineageTag: 17a151b1-5771-4a7a-a2b6-d14d2bcac0b0

	measure Revenue = SUM(FactSales[Revenue])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Revenue
		lineageTag: 0db23b9e-6c87-413f-b13d-9c1c3016d925

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure Profit = SUM(FactSales[Profit])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Profit
		lineageTag: 2bb0dc1b-5cbb-4588-843e-7d68fe5b0124

	measure Discount = SUM(FactSales[Discount])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Cost
		lineageTag: c13f21ee-9cc2-42ef-889f-f10c615dbeae

	measure Order = COUNT(FactSales[OrderID])
		formatString: #,0.00
		displayFolder: Order/Quantity
		lineageTag: 261a12a7-71a9-4b8c-a433-a26bfb098529

	measure Quantity = SUM(FactSales[UnitsSold])
		formatString: #,0.00
		displayFolder: Quantity
		lineageTag: 35a6ba9e-563a-45db-9092-5baa02fc88c0

	measure Total_Sales = SUM(FactSales[GrossRevenue])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		isHidden
		displayFolder: Others
		lineageTag: 8d213578-dbe5-44b8-b744-7e772f16b552

	measure Cost = SUM(FactSales[Cost])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Cost
		lineageTag: fe19268e-6095-42f4-a458-101577d20285

	measure 'Discount % of Sales' = DIVIDE([Discount],[Revenue])
		displayFolder: Cost
		lineageTag: 7e594db2-5c2d-4a7a-8b2f-b44aa1e39296

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue LastYear' = CALCULATE([Revenue],SAMEPERIODLASTYEAR(DimDate[Date]))
		displayFolder: Revenue\Revenue More
		lineageTag: 02777561-bf01-4573-a590-562a5115288f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue YoY' = [Revenue] - [Revenue LastYear]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Revenue\Revenue More
		lineageTag: 8379e150-0f12-4b3d-9a1a-d1ee4569ff8b

	measure 'Revenue YoY %' = DIVIDE ( [Revenue YoY], [Revenue LastYear] )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Revenue\Revenue More
		lineageTag: 8c861e0b-cf28-4370-b64b-d9f4e8236b51

	measure 'Revenue YTD' = TOTALYTD ( [Revenue], DimDate[Date])
		displayFolder: Revenue\Revenue More
		lineageTag: d7787938-e3a4-4381-bb34-6cf34210e920

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Title_Category =
			IF(
			    SELECTEDVALUE(DimProduct[Category]) <> BLANK(),
			    "Total Sales of " & SELECTEDVALUE(DimProduct[Category]),
			    "Total Sales")
		isHidden
		displayFolder: Others
		lineageTag: d466dbf4-4e16-41c4-8569-1642cf6728f9

	measure 'Median Revenue' = MEDIAN(FactSales[Revenue])
		displayFolder: Revenue
		lineageTag: bfecffb1-f7b0-4b8f-b3e4-2dd82756e7ae

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Orders PY Var' = [Order]- [Order PY]
		formatString: 0
		displayFolder: Order/Quantity
		lineageTag: f592af18-70b4-4200-a27e-4ac4485529e8

	measure 'YoY Growth %' = ```
			
			DIVIDE(
			    [Quantity] - [Orders PY Var],
			    [Orders PY Var]
			) 
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Others
		lineageTag: 04b23cce-d2bc-469e-b162-da007c4c1c9e

	measure 'Order PY' = ```
			CALCULATE([Order], 
			    DATEADD(DimDate[Date], 1, YEAR)
			)
			```
		formatString: 0
		displayFolder: Order/Quantity
		lineageTag: 9c1a3b5f-56f8-4c83-9253-e71ecdf28299

	measure 'Revenue PY' = CALCULATE( [Revenue], DATEADD(DimDate[Date], -1, YEAR))
		displayFolder: Revenue
		lineageTag: 6e1de3b5-f0ac-4252-a7bb-4a1aedf34460

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue PY Var' = [Revenue] - [Revenue PY]
		displayFolder: Revenue
		lineageTag: 85ef57c5-03e8-463c-8811-c3801849c904

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue PY Var %' = DIVIDE( [Revenue PY Var], [Revenue], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Revenue
		lineageTag: 73e5c603-3f6b-42b8-aa54-123e85b503ce

	measure 'FMT Revenue PY Var %' = FORMAT([Revenue PY Var %], "▲ 0.0%; ▼ 0.0%; 0.0%")
		displayFolder: Revenue
		lineageTag: 00627f8c-14ce-47ad-a17c-9cf312bbd411

	measure 'Profit PY' = CALCULATE([Profit], DATEADD(DimDate[Date], -1,YEAR))
		displayFolder: Profit
		lineageTag: 890983a5-8499-47ae-bee0-867bbc8477ad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit PY Var' = [Profit] - [Profit PY]
		displayFolder: Profit
		lineageTag: 58af8953-43a8-4d3b-982c-7e1d92e41635

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit PY Var %' = DIVIDE([Profit PY Var], [Profit],0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Profit
		lineageTag: ba8e1aad-0f95-4acf-9eb4-0e92d1075648

	measure 'FMT Profit PY Var %' = FORMAT([Profit PY Var %], "▲ 0.0%; ▼ 0.0%; 0.0%")
		displayFolder: Profit
		lineageTag: 9faeb8d4-dbe4-4f96-81ac-b3dfa2411106

	measure 'Profit Margin %' = ```
			DIVIDE([Profit], [Revenue], 0)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Profit
		lineageTag: 67ac6193-c7d6-4aef-8fcd-9c070205ca13

	measure 'Total Unit Sold' = SUM(FactSales[UnitsSold])
		formatString: 0
		displayFolder: Others
		lineageTag: 5b615a82-4bc1-4660-8c5c-7f851eb57df1

	measure 'Order PY Var %' = DIVIDE( [Orders PY Var], [Order], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Order/Quantity
		lineageTag: 6f289ff6-e03e-4ad1-92a8-d43a44d67ef3

	measure 'Cost PY' = ```
			CALCULATE([Cost], 
			    DATEADD(DimDate[Date], 1, YEAR)
			)
			```
		formatString: 0
		displayFolder: Cost
		lineageTag: e4d9902a-3386-440a-b425-7ea96919b928

	measure 'Cost PY Var' = [Cost]- [Cost PY]
		displayFolder: Cost
		lineageTag: c2a4f6bf-3bf6-4fcc-babb-6dadc2558f31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cost PY Var %' = DIVIDE( [Cost PY Var], [Cost], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Cost
		lineageTag: ed61add1-2cb6-46ba-8214-158f5bd4143f

	measure 'Quantity PY' = ```
			CALCULATE([Quantity], 
			    DATEADD(DimDate[Date], 1, YEAR)
			)
			```
		formatString: 0
		displayFolder: Quantity
		lineageTag: f482c98a-6d23-46b2-a87e-8b56e3d9a0d3

	measure 'Quantity PY Var' = [Quantity]- [Quantity PY]
		formatString: 0
		displayFolder: Quantity
		lineageTag: 5fd8d659-c4b5-4a86-873d-703c5cba9903

	measure 'Quantity PY Var %' = DIVIDE([Quantity PY Var], [Quantity],0)
		displayFolder: Quantity
		lineageTag: e985015f-751f-4d58-8565-3af695f51da6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FMT Quantity PY Var %' = FORMAT([Quantity PY Var %], "▲ 0.0%; ▼ 0.0%; 0.0%")
		displayFolder: Quantity
		lineageTag: c8798da1-2911-4852-96c4-c5dbc835d02e

	measure 'FMT Cost PY Var %' = FORMAT([Cost PY Var %], "▲ 0.0%; ▼ 0.0%; 0.0%")
		displayFolder: Cost
		lineageTag: 328aeed8-cde4-47af-b2fa-8fa503514361

	measure 'FMT Order PY Var %' = FORMAT([Order PY Var %], "▲ 0.0%; ▼ 0.0%; 0.0%")
		displayFolder: Order/Quantity
		lineageTag: cad7f252-fc65-4f91-bec5-675fbcebc5d5

	column Column
		isHidden
		formatString: 0
		lineageTag: da75f384-1d1b-4c80-970b-4be3466318ab
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _Measure = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 23af02c24a4a4769998438ac4bc41404

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

