table DimCustomer
	lineageTag: bf8e4cc5-21e0-4cf3-bb59-064226b3c53f

	column CustomerID
		dataType: string
		lineageTag: d4857497-6956-4ca4-98d8-ef004aeab203
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: 91204c12-de3f-4c08-96c3-98b98678c596
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column CustomerSegment
		dataType: string
		lineageTag: f77b9143-e667-4c58-8719-bd828eeca36a
		summarizeBy: none
		sourceColumn: CustomerSegment

		annotation SummarizationSetBy = Automatic

	column PaymentMode
		dataType: string
		lineageTag: 0dc5b5e1-fc1f-4aac-89a6-18fd97c6f018
		summarizeBy: none
		sourceColumn: PaymentMode

		annotation SummarizationSetBy = Automatic

	partition DimCustomer = m
		mode: import
		queryGroup: 'All Tables'
		source = ```
				let
				    // Load all files from the folder
				    SourceFolder = Folder.Files(Sources),
				    
				    // Filter to get the specific CSV file
				    FilteredFile = Table.SelectRows(SourceFolder, each [Name] = "DC Sales Information.csv"),
				    
				    // Get the file content
				    FileContent = Csv.Document(FilteredFile{0}[Content], [Delimiter=",", Columns=22, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    
				    // Promote headers
				    #"Promoted Headers" = Table.PromoteHeaders(FileContent, [PromoteAllScalars=true]),
				    
				    // Change column types
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{
				        {"OrderID", type text}, {"OrderDate", type date}, {"CustomerID", type text}, {"CustomerName", type text},
				        {"CustomerSegment", type text}, {"Region", type text}, {"Country", type text}, {"City", type text},
				        {"PostalCode", Int64.Type}, {"ProductID", type text}, {"ProductName", type text}, {"Category", type text},
				        {"SubCategory", type text}, {"SalesChannel", type text}, {"UnitsSold", Int64.Type}, {"UnitPrice", type number},
				        {"Revenue", type number}, {"Cost", type number}, {"Profit", type number}, {"Discount", type number},
				        {"PaymentMode", type text}, {"DeliveryDate", type date}
				    }),
				
				    // Remove duplicates
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type"),
				
				    // Create CustomerName2
				    #"Inserted Merged Column" = Table.AddColumn(#"Removed Duplicates", "Merged", each Text.Combine({"Customer_", [CustomerID]}), type text),
				    #"Reordered Columns" = Table.ReorderColumns(#"Inserted Merged Column",{"OrderID", "OrderDate", "CustomerID", "CustomerName", "Merged", "CustomerSegment", "Region", "Country", "City", "PostalCode", "ProductID", "ProductName", "Category", "SubCategory", "SalesChannel", "UnitsSold", "UnitPrice", "Revenue", "Cost", "Profit", "Discount", "PaymentMode", "DeliveryDate"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Merged", "CustomerName2"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"CustomerName"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"CustomerName2", "CustomerName"}}),
				
				    // Fix category names
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1","electronix","Electronics",Replacer.ReplaceText,{"Category"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Furnture","Furniture",Replacer.ReplaceText,{"Category"}),
				
				    // Sort and clean region
				    #"Sorted Rows" = Table.Sort(#"Replaced Value1",{{"Country", Order.Ascending}, {"City", Order.Ascending}, {"Region", Order.Ascending}, {"CustomerSegment", Order.Ascending}}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Sorted Rows","","Missing",Replacer.ReplaceValue,{"Region"}),
				
				    // Clean and format text
				    #"Trimmed Text" = Table.TransformColumns(Table.TransformColumnTypes(#"Replaced Value2", {{"PostalCode", type text}}, "en-US"),{{"Region", Text.Trim, type text}, {"Country", Text.Trim, type text}, {"City", Text.Trim, type text}, {"PostalCode", Text.Trim, type text}}),
				    #"Uppercased Text" = Table.TransformColumns(#"Trimmed Text",{{"Region", Text.Upper, type text}, {"Country", Text.Upper, type text}, {"City", Text.Upper, type text}, {"PostalCode", Text.Upper, type text}}),
				
				    // Final GeoID
				    #"Inserted Merged Column2" = Table.AddColumn(#"Uppercased Text", "Merged", each Text.Combine({[Region], "|", [Country], "|", [City], "|", [PostalCode]}), type text),
				    #"Renamed Columns3" = Table.RenameColumns(#"Inserted Merged Column2",{{"Merged", "GeoID"}}),
				
				    // Final formatting
				    #"Capitalized Each Word" = Table.TransformColumns(#"Renamed Columns3",{{"Region", Text.Proper, type text}, {"Country", Text.Proper, type text}, {"City", Text.Proper, type text}}),
				    #"Sorted Rows1" = Table.Sort(#"Capitalized Each Word",{{"OrderDate", Order.Descending}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Sorted Rows1",{"CustomerID", "CustomerName", "CustomerSegment", "PaymentMode"}),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Other Columns"),
				    #"Removed Duplicates2" = Table.Distinct(#"Removed Duplicates1", {"CustomerID"})
				in
				    #"Removed Duplicates2"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

