table DimProduct
	lineageTag: 8444eefd-8c53-4006-818c-a47c7d6a96bf

	column ProductID
		dataType: string
		lineageTag: a2de974d-6915-4ef2-a35b-5420aeb87403
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 3428f3a1-bafe-48b9-9891-0c53644015ad
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: f64422bb-f32c-4d50-a93b-6bd97f2a3986
		summarizeBy: none
		sourceColumn: Category

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column SubCategory
		dataType: string
		lineageTag: db46c603-e11f-4f5f-a4f5-9bc391ae37f8
		summarizeBy: none
		sourceColumn: SubCategory

		annotation SummarizationSetBy = Automatic

	column SalesChannel
		dataType: string
		lineageTag: 73df6b3f-47bb-49d2-b150-27753c8970bd
		summarizeBy: none
		sourceColumn: SalesChannel

		annotation SummarizationSetBy = Automatic

	partition DimProduct = m
		mode: import
		queryGroup: 'All Tables'
		source = ```
				let
				    // Load all files from the folder
				    SourceFolder = Folder.Files(Sources),
				    
				    // Filter to get the specific CSV file
				    FilteredFile = Table.SelectRows(SourceFolder, each [Name] = "DC Sales Information.csv"),
				    
				    // Get the file content
				    FileContent = Csv.Document(FilteredFile{0}[Content], [Delimiter=",", Columns=22, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    
				    // Promote headers
				    #"Promoted Headers" = Table.PromoteHeaders(FileContent, [PromoteAllScalars=true]),
				    
				    // Change column types
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{
				        {"OrderID", type text}, {"OrderDate", type date}, {"CustomerID", type text}, {"CustomerName", type text},
				        {"CustomerSegment", type text}, {"Region", type text}, {"Country", type text}, {"City", type text},
				        {"PostalCode", Int64.Type}, {"ProductID", type text}, {"ProductName", type text}, {"Category", type text},
				        {"SubCategory", type text}, {"SalesChannel", type text}, {"UnitsSold", Int64.Type}, {"UnitPrice", type number},
				        {"Revenue", type number}, {"Cost", type number}, {"Profit", type number}, {"Discount", type number},
				        {"PaymentMode", type text}, {"DeliveryDate", type date}
				    }),
				
				    // Remove duplicates
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type"),
				
				    // Create CustomerName2
				    #"Inserted Merged Column" = Table.AddColumn(#"Removed Duplicates", "Merged", each Text.Combine({"Customer_", [CustomerID]}), type text),
				    #"Reordered Columns" = Table.ReorderColumns(#"Inserted Merged Column",{"OrderID", "OrderDate", "CustomerID", "CustomerName", "Merged", "CustomerSegment", "Region", "Country", "City", "PostalCode", "ProductID", "ProductName", "Category", "SubCategory", "SalesChannel", "UnitsSold", "UnitPrice", "Revenue", "Cost", "Profit", "Discount", "PaymentMode", "DeliveryDate"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Merged", "CustomerName2"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"CustomerName"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"CustomerName2", "CustomerName"}}),
				
				    // Fix category names
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1","electronix","Electronics",Replacer.ReplaceText,{"Category"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Furnture","Furniture",Replacer.ReplaceText,{"Category"}),
				
				    // Sort and clean region
				    #"Sorted Rows" = Table.Sort(#"Replaced Value1",{{"Country", Order.Ascending}, {"City", Order.Ascending}, {"Region", Order.Ascending}, {"CustomerSegment", Order.Ascending}}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Sorted Rows","","Missing",Replacer.ReplaceValue,{"Region"}),
				
				    // Clean and format text
				    #"Trimmed Text" = Table.TransformColumns(Table.TransformColumnTypes(#"Replaced Value2", {{"PostalCode", type text}}, "en-US"),{{"Region", Text.Trim, type text}, {"Country", Text.Trim, type text}, {"City", Text.Trim, type text}, {"PostalCode", Text.Trim, type text}}),
				    #"Uppercased Text" = Table.TransformColumns(#"Trimmed Text",{{"Region", Text.Upper, type text}, {"Country", Text.Upper, type text}, {"City", Text.Upper, type text}, {"PostalCode", Text.Upper, type text}}),
				
				    // Final GeoID
				    #"Inserted Merged Column2" = Table.AddColumn(#"Uppercased Text", "Merged", each Text.Combine({[Region], "|", [Country], "|", [City], "|", [PostalCode]}), type text),
				    #"Renamed Columns3" = Table.RenameColumns(#"Inserted Merged Column2",{{"Merged", "GeoID"}}),
				
				    // Final formatting
				    #"Capitalized Each Word" = Table.TransformColumns(#"Renamed Columns3",{{"Region", Text.Proper, type text}, {"Country", Text.Proper, type text}, {"City", Text.Proper, type text}}),
				    #"Sorted Rows1" = Table.Sort(#"Capitalized Each Word",{{"OrderDate", Order.Descending}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Sorted Rows1",{"SalesChannel", "SubCategory", "Category", "ProductName", "ProductID"}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Removed Other Columns",{"ProductID", "ProductName", "Category", "SubCategory", "SalesChannel"}),
				    #"Removed Duplicates1" = Table.Distinct(#"Reordered Columns1"),
				    #"Removed Duplicates2" = Table.Distinct(#"Removed Duplicates1"),
				    #"Removed Duplicates3" = Table.Distinct(#"Removed Duplicates2", {"ProductID"}),
				    // Filter ProductID for P0245 and P0450, then replace Category "Furniture" to "Electronics"
				    #"Filtered Products" = Table.SelectRows(#"Removed Duplicates3", each [ProductID] = "P0245" or [ProductID] = "P0450"),
				    #"Replaced Category" = Table.ReplaceValue(#"Filtered Products", "Furniture", "Electronics", Replacer.ReplaceText, {"Category"}),
				
				    // Combine filtered rows with the rest
				    #"Combined Rows" = Table.Combine({Table.SelectRows(#"Removed Duplicates3", each [ProductID] <> "P0245" and [ProductID] <> "P0450"), #"Replaced Category"})
				in
				    #"Combined Rows"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

