table FactSales
	lineageTag: f5d2caf5-3bbe-4c66-ae7d-65a55ac90bf2

	column OrderID
		dataType: string
		lineageTag: 1748f8b2-194f-4723-b75c-be0695e0f858
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 028faf91-e6da-4406-8fbe-54d06a3528e0
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerID
		dataType: string
		lineageTag: 38f66e43-fa22-45d2-95be-69ad2e3530fe
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column UnitsSold
		dataType: int64
		formatString: 0
		lineageTag: 035720ba-e42d-4379-bcc5-00c0322f4683
		summarizeBy: sum
		sourceColumn: UnitsSold

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: ad39cc58-be9a-419d-8d39-5508774fe674
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

	column Revenue
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 41066d04-f809-47f0-84bf-ae49944d451b
		summarizeBy: sum
		sourceColumn: Revenue

		annotation SummarizationSetBy = Automatic

	column Cost
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 9ee10cbc-536f-4288-82cf-6e080725a8ce
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b2c4fbff-7315-4954-80cf-5411d0a67ca5
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: ee087f85-fcdf-42c7-b313-6d9c0ae5a9fc
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DeliveryDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8763db99-b757-45fa-874d-9d7cbf2817f4
		summarizeBy: none
		sourceColumn: DeliveryDate

		variation Variation
			isDefault
			relationship: 84b0a54e-3519-4273-822a-e60a3290d9c8
			defaultHierarchy: LocalDateTable_d3d0dd17-f154-4e87-8a24-ef28b86d978f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ProductID
		dataType: string
		lineageTag: 5334ffad-86bf-4ee0-9c74-b69737f2ffc6
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column GeoID
		dataType: string
		lineageTag: 0c792c7a-6462-4659-a40f-4ae5c2e07b15
		summarizeBy: none
		sourceColumn: GeoID

		annotation SummarizationSetBy = Automatic

	column GrossRevenue
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: db9269d2-7b7c-464f-b2f4-384e5a16414c
		summarizeBy: sum
		sourceColumn: GrossRevenue

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column DiscountValue
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 1a0c4ad4-16c3-463b-9d3d-ba5541ef333d
		summarizeBy: sum
		sourceColumn: DiscountValue

		annotation SummarizationSetBy = Automatic

	partition FactSales = m
		mode: import
		queryGroup: 'All Tables'
		source = ```
				let
				    // Load all files from the folder
				    SourceFolder = Folder.Files(Sources),
				    
				    // Filter to get the specific CSV file
				    FilteredFile = Table.SelectRows(SourceFolder, each [Name] = "DC Sales Information.csv"),
				    
				    // Get the file content
				    FileContent = Csv.Document(FilteredFile{0}[Content], [Delimiter=",", Columns=22, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    
				    // Promote headers
				    #"Promoted Headers" = Table.PromoteHeaders(FileContent, [PromoteAllScalars=true]),
				    
				    // Change column types
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{
				        {"OrderID", type text}, {"OrderDate", type date}, {"CustomerID", type text}, {"CustomerName", type text},
				        {"CustomerSegment", type text}, {"Region", type text}, {"Country", type text}, {"City", type text},
				        {"PostalCode", Int64.Type}, {"ProductID", type text}, {"ProductName", type text}, {"Category", type text},
				        {"SubCategory", type text}, {"SalesChannel", type text}, {"UnitsSold", Int64.Type}, {"UnitPrice", type number},
				        {"Revenue", type number}, {"Cost", type number}, {"Profit", type number}, {"Discount", type number},
				        {"PaymentMode", type text}, {"DeliveryDate", type date}
				    }),
				
				    // Remove duplicates
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type"),
				
				    // Create CustomerName2
				    #"Inserted Merged Column" = Table.AddColumn(#"Removed Duplicates", "Merged", each Text.Combine({"Customer_", [CustomerID]}), type text),
				    #"Reordered Columns" = Table.ReorderColumns(#"Inserted Merged Column",{"OrderID", "OrderDate", "CustomerID", "CustomerName", "Merged", "CustomerSegment", "Region", "Country", "City", "PostalCode", "ProductID", "ProductName", "Category", "SubCategory", "SalesChannel", "UnitsSold", "UnitPrice", "Revenue", "Cost", "Profit", "Discount", "PaymentMode", "DeliveryDate"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Merged", "CustomerName2"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"CustomerName"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"CustomerName2", "CustomerName"}}),
				
				    // Fix category names
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1","electronix","Electronics",Replacer.ReplaceText,{"Category"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Furnture","Furniture",Replacer.ReplaceText,{"Category"}),
				
				    // Sort and clean region
				    #"Sorted Rows" = Table.Sort(#"Replaced Value1",{{"Country", Order.Ascending}, {"City", Order.Ascending}, {"Region", Order.Ascending}, {"CustomerSegment", Order.Ascending}}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Sorted Rows","","Missing",Replacer.ReplaceValue,{"Region"}),
				
				    // Clean and format text
				    #"Trimmed Text" = Table.TransformColumns(Table.TransformColumnTypes(#"Replaced Value2", {{"PostalCode", type text}}, "en-US"),{{"Region", Text.Trim, type text}, {"Country", Text.Trim, type text}, {"City", Text.Trim, type text}, {"PostalCode", Text.Trim, type text}}),
				    #"Uppercased Text" = Table.TransformColumns(#"Trimmed Text",{{"Region", Text.Upper, type text}, {"Country", Text.Upper, type text}, {"City", Text.Upper, type text}, {"PostalCode", Text.Upper, type text}}),
				
				    // Final GeoID
				    #"Inserted Merged Column2" = Table.AddColumn(#"Uppercased Text", "Merged", each Text.Combine({[Region], "|", [Country], "|", [City], "|", [PostalCode]}), type text),
				    #"Renamed Columns3" = Table.RenameColumns(#"Inserted Merged Column2",{{"Merged", "GeoID"}}),
				
				    // Final formatting
				    #"Capitalized Each Word" = Table.TransformColumns(#"Renamed Columns3",{{"Region", Text.Proper, type text}, {"Country", Text.Proper, type text}, {"City", Text.Proper, type text}}),
				    #"Sorted Rows1" = Table.Sort(#"Capitalized Each Word",{{"OrderDate", Order.Descending}}),
				
				    // Remove unnecessary columns
				    #"Removed Columns2" = Table.RemoveColumns(#"Sorted Rows1",{"CustomerName", "CustomerSegment", "Region", "Country", "City", "ProductName", "Category", "SubCategory", "PostalCode", "SalesChannel", "PaymentMode"}),
				    #"Inserted Merged Column1" = Table.AddColumn(#"Removed Columns2", "GrossRevenue", each Text.Combine({"=", Text.From([UnitsSold], "en-US"), "*", Text.From([UnitPrice], "en-US")}), type text),
				    #"Added Custom" = Table.AddColumn(#"Inserted Merged Column1", "GrossRevenu", each [UnitsSold] * [UnitPrice]),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Added Custom",{"OrderID", "OrderDate", "CustomerID", "ProductID", "UnitsSold", "UnitPrice", "Revenue", "Cost", "Profit", "Discount", "DeliveryDate", "GeoID", "GrossRevenu", "GrossRevenue"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns1",{"GrossRevenue"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns1",{{"GrossRevenu", "GrossRevenue"}}),
				    #"Reordered Columns2" = Table.ReorderColumns(#"Renamed Columns2",{"OrderID", "OrderDate", "CustomerID", "ProductID", "UnitsSold", "UnitPrice", "GrossRevenue", "Discount", "Revenue", "Cost", "Profit", "DeliveryDate", "GeoID"}),
				    #"Added Custom1" = Table.AddColumn(#"Reordered Columns2", "DiscountValue", each [GrossRevenue] *[Discount]),
				    #"Reordered Columns3" = Table.ReorderColumns(#"Added Custom1",{"OrderID", "OrderDate", "CustomerID", "ProductID", "UnitsSold", "UnitPrice", "GrossRevenue", "Discount", "DiscountValue", "Revenue", "Cost", "Profit", "DeliveryDate", "GeoID"}),
				    #"Added Custom2" = Table.AddColumn(#"Reordered Columns3", "NetRevenue", each [GrossRevenue] -[DiscountValue]),
				    #"Reordered Columns4" = Table.ReorderColumns(#"Added Custom2",{"OrderID", "OrderDate", "CustomerID", "ProductID", "UnitsSold", "UnitPrice", "GrossRevenue", "Discount", "DiscountValue", "NetRevenue", "Revenue", "Cost", "Profit", "DeliveryDate", "GeoID"}),
				    #"Rounded Off" = Table.TransformColumns(#"Reordered Columns4",{{"DiscountValue", each Number.Round(_, 2), type number}}),
				    #"Rounded Off1" = Table.TransformColumns(#"Rounded Off",{{"NetRevenue", each Number.Round(_, 2), type number}}),
				    #"Removed Columns3" = Table.RemoveColumns(#"Rounded Off1",{"NetRevenue"})
				in
				    #"Removed Columns3"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

